### ISSUE TITLE
Is this complying with the Apple App Store and Google Play Store?

### ISSUE THREAD

**Issue by YazeedAlKhalaf** [Waytoon/chimera_flutter_code_push#1]
I believe using this SDK is against the app stores rules and policies. Although apps like:
* Instagram
* Facebook
* YouTube
* Gmail
are using a similar approach but they are not a small indie developer, so they wouldn't shut their developer accounts. So is it safe to use chimera in a Flutter app and publish it to the stores, Apple App Store, and Google Play Store?

**Comment by Waytoon** [comment]
Thanks, Yazeed. Currently, we are only focusing on code push solutions and technology. Also, we implemented chimera SDK with the full dart compilation, it could be much more capable and similar to the original flutter app.

**Comment by Waytoon** [comment]
According to the current situation, we would like to answer this very carefully. It is a sensitive topic but we would not commit it , but it could be a capable soulution...
