### ISSUE TITLE
Where is wtbase folder?

### ISSUE THREAD

**Issue by rohitranjan1991** [Waytoon/chimera_flutter_code_push#2]
I cannot find the wtbase folder to download ? where can i download it from ?

**Comment by Aaron009** [comment]
It is downloaded from the release tool to run under the compile tool directory. We're going to make a video tutorial, because most of us still feel it's difficult to get started.

**Comment by Aaron009** [comment]
@rohitranjan1991 Hi, is it all right?

**Comment by rohitranjan1991** [comment]
Hi @Aaron009, what is the release tool here? If not a video tutorial, can you quickly write down the steps that I can quickly follow to get started with this. I am planning to demo this in my company next week.

**Comment by Waytoon** [comment]
Hi @rohitranjan1991  How can I help you? Do you have any account for real-time chat, such as wechat or facetime? I think we can have a chat in person instead of adding content here :-)

**Comment by Waytoon** [comment]
And we can show you a detailed instructions or do Teamviewer...

**Comment by rohitranjan1991** [comment]
Thanks @Waytoon for replying... my mail id is 91.rohit@gmail.com. We can have a gmail chat if that works for you.

**Comment by KieranLafferty** [comment]
Would be great to get an explanation here. Interested in checking out the tool but will only be helpful for everyone if the info is widely available

**Comment by Waytoon** [comment]
Sorry for the confusion in the readme instruction. I will update the instruction on how to do integration later.  It could be a more detailed explanation. And please re-download the 'rust_compile' in release tab.

**Comment by Aaron009** [comment]
> Would be great to get an explanation here. Interested in checking out the tool but will only be helpful for everyone if the info is widely available

The tutorial has been updated. You can read the Readme

**Comment by Waytoon** [comment]
Refer to readme, there is a new detailed instruction on how to generate 'wtbase'.

**Comment by Waytoon** [comment]
Refer to readme, there is a new detailed instruction on how to generate 'wtbase'.
