### ISSUE TITLE
ios编译运行失败

### ISSUE THREAD

**Issue by siyukok** [Waytoon/chimera_flutter_code_push#6]
**Describe the bug**
Android端集成成功，正常运行，iOS侧，运行时找不到mylib-Swift.h文件，flutter packages get以及pod install均已执行过

**Screenshots**
![image](https://user-images.githubusercontent.com/21030561/110920177-0b9aff00-8358-11eb-9f4e-e2fda353fd8b.png)

flutter 环境
Flutter 1.22.6 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9b2d32b605 (7 weeks ago) • 2021-01-22 14:36:39 -0800
Engine • revision 2f0af37152
Tools • Dart 2.10.5

**Comment by Aaron009** [comment]
非常对不起，编译器搞错了。
wtbase/ios文件目录，凡是文件名包含mylib的全部删掉。
我早点更新掉这个问题

**Comment by siyukok** [comment]
好的，感谢开源，希望这个库早日达到生产上线水平👍

**Comment by siyukok** [comment]
删掉mylib相关后，正常运行
